#!/usr/bin/env node

const cp = require("child_process");
const chalk = require("chalk");
const config = require("./config");
const { run } = require("./utils");
require("dotenv").config({ path: config.envPath });

const containerName = process.env.CONFIGURATOR_NAME;
const userName = process.env.USER_NAME;
const masterIp = process.env.K8S_MASTER;
const slaveIp = process.env.K8S_SLAVE;
const runMaster = run();
const runSlave = run({ isMaster: false });

console.log(
  chalk.blue(`📃 Clean up docker containers on ${masterIp} and ${slaveIp}`)
);

try {
  console.log(chalk.blue(`First up, delete all pods on ${slaveIp}`));
  runMaster(`kubectl delete pods --all --grace-period=0 --force`);

  runMaster(`kubectl get pods`);
  runSlave("docker ps -a");
} catch (error) {
  console.log(error);
  console.log(chalk.red(`Oops, failed to delete pods...`));
}

console.log(chalk.blue(`Next up, let's delete Configurator on ${masterIp}`));

try {
  const hasContainer = cp
    .execSync(
      `ssh ${userName}@${masterIp} docker ps --filter "name=${containerName}" -q`
    )
    .toString();

  if (hasContainer) {
    runMaster(`docker rm -f ${containerName}`);

    console.log(
      chalk.green(
        `👍 Successfully deleted container: ${chalk.bold(containerName)}`
      )
    );
    return;
  }

  console.log();
  console.log(
    chalk.yellow(
      `Could not find a container named ${chalk.bold(containerName)}`
    )
  );

  console.log(
    chalk.blue(
      "Here are some more info of the currently running configurator container:"
    )
  );
  runMaster("docker ps -a");
} catch (error) {
  console.log(error);
  console.log(
    chalk.red(`Oops, failed to remove container ${chalk.bold(containerName)}`)
  );
}
