#!/usr/bin/env node

const sha = require('sha.js');
const chalk = require('chalk');

const defaultHashOptions = {
  algorithm: 'sha256',
  encode: 'hex',
  maxLength: 8,
};

const hash = (input = '', options = defaultHashOptions) =>
  sha(options.algorithm)
    .update(input)
    .digest(options.encode)
    .substring(0, options.maxLength + 1);

const [, , group, name] = process.argv;

if (!group || !name) {
  console.log(chalk.red(`Did you provide correct input arguments?`));
  console.log(chalk.yellow(`Usage: createHash group name`));
} else {
  console.log(chalk.green(`Hash created: ${hash(`${group}${name}`)}`));
}
