#!/usr/bin/env node

const config = require("./config");
const chalk = require("chalk");
const axios = require("axios");
require("dotenv").config({ path: config.envPath });

const API_ROOT = process.env.API_ROOT;
const SLAVE_IP = process.env.K8S_SLAVE;

console.log(chalk.blue(`📃 Deleting all services running on ${SLAVE_IP}`));

const CONNECTOR_URL = `${API_ROOT}/connectors`;
const STREAM_URL = `${API_ROOT}/streams`;
const SHABONDI_URL = `${API_ROOT}/shabondis`;
const TOPIC_URL = `${API_ROOT}/topics`;
const WORKER_URL = `${API_ROOT}/workers`;
const BROKER_URL = `${API_ROOT}/brokers`;
const ZOOKEEPER_URL = `${API_ROOT}/zookeepers`;
const PIPELINE_URL = `${API_ROOT}/pipelines`;
const NODE_URL = `${API_ROOT}/nodes`;
const OBJECT_URL = `${API_ROOT}/objects`;

(async () => {
  await deleteAllServices();
})();

async function deleteAllServices() {
  // delete all connectors
  const connectorResponse = await axios.get(CONNECTOR_URL);
  await Promise.all(
    connectorResponse.data.map(async ({ group, name }) => {
      await axios.put(`${CONNECTOR_URL}/${name}/stop?group=${group}`);
      await axios.delete(`${CONNECTOR_URL}/${name}?group=${group}`);
    })
  );

  const streamResponse = await axios.get(STREAM_URL);
  await Promise.all(
    streamResponse.data.map(async ({ group, name }) => {
      await axios.put(`${STREAM_URL}/${name}/stop?group=${group}`);
      await axios.delete(`${STREAM_URL}/${name}?group=${group}`);
    })
  );

  const shabondiResponse = await axios.get(SHABONDI_URL);
  await Promise.all(
    shabondiResponse.data.map(async ({ group, name }) => {
      await axios.put(`${SHABONDI_URL}/${name}/stop?group=${group}`);
      await axios.delete(`${SHABONDI_URL}/${name}?group=${group}`);
    })
  );

  const topicResponse = await axios.get(TOPIC_URL);
  await Promise.all(
    topicResponse.data.map(async ({ group, name }) => {
      await axios.put(`${TOPIC_URL}/${name}/stop?group=${group}`);
      await axios.delete(`${TOPIC_URL}/${name}?group=${group}`);
    })
  );

  const workerResponse = await axios.get(WORKER_URL);
  await Promise.all(
    workerResponse.data.map(async ({ group, name }) => {
      await axios.put(`${WORKER_URL}/${name}/stop?group=${group}`);
      await axios.delete(`${WORKER_URL}/${name}?group=${group}`);
    })
  );

  const brokerResponse = await axios.get(BROKER_URL);
  await Promise.all(
    brokerResponse.data.map(async ({ group, name }) => {
      await axios.put(`${BROKER_URL}/${name}/stop?group=${group}`);
      await axios.delete(`${BROKER_URL}/${name}?group=${group}`);
    })
  );

  const zookeeperResponse = await axios.get(ZOOKEEPER_URL);
  await Promise.all(
    zookeeperResponse.data.map(async ({ group, name }) => {
      await axios.put(`${ZOOKEEPER_URL}/${name}/stop?group=${group}`);
      await axios.delete(`${ZOOKEEPER_URL}/${name}?group=${group}`);
    })
  );

  const pipelineResponse = await axios.get(PIPELINE_URL);
  await Promise.all(
    pipelineResponse.data.map(async ({ group, name }) => {
      await axios.delete(`${PIPELINE_URL}/${name}?group=${group}`);
    })
  );

  const nodeResponse = await axios.get(NODE_URL);
  await Promise.all(
    nodeResponse.data.map(async ({ hostname }) => {
      await axios.delete(`${NODE_URL}/${hostname}`);
    })
  );

  const objectResponse = await axios.get(OBJECT_URL);
  await Promise.all(
    objectResponse.data.map(async ({ group, name }) => {
      await axios.delete(`${OBJECT_URL}/${name}?group=${group}`);
    })
  );
}

// async function waitUntil(retryUrl, checkBreakCondition) {
//   const maxRetry = 5;
//   let retryCount = 0;
//   const sleepTime = 2000;

//   while (retryCount < maxRetry) {
//     try {
//       const response = await retryUrl();
//       if (checkBreakCondition(response)) return response;
//     } catch (error) {
//       console.log("retry API failed but we will continue to execute: ", error);
//     }

//     await sleep(sleepTime);
//     retryCount++;
//   }
// }

// function isStopped(response) {
//   return typeof response.data.state === "undefined";
// }

// const waitForRunning = (res) => res.data.state === SERVICE_STATE.RUNNING;

// const waitForClassInfosReady = (res) => !isEmpty(res.data.classInfos);

// const waitForTopicReady = (res) => res.data.state === SERVICE_STATE.RUNNING;

// const wait = async ({
//   api,
//   objectKey,
//   checkFn,
//   checkParam,
//   maxRetry = 10,
//   sleep = 2000,
// }: {
//   api: API,
//   objectKey,
//   checkFn: (res, params) => boolean,
//   checkParam?: object,
//   maxRetry?: number,
//   sleep?: number,
// }) => {
//   let retryCount = 0;
//   while (retryCount < maxRetry) {
//     try {
//       const res =
//         (await api.get) <
//         T >
//         {
//           name: objectKey.name,
//           queryParams: { group: objectKey.group },
//         };
//       if (checkFn(res, checkParam)) {
//         return res;
//       }
//     } catch (error) {
//       //Something went wrong, but we still retry until exceed maxRetry
//       // eslint-disable-next-line no-console
//       console.log("retry API failed but we will continue to execute: ", error);
//     }

//     await commonUtils.sleep(sleep);
//     retryCount++;
//   }
//   const errorRes: BasicResponse = {
//     data: {
//       error: {
//         code: "N/A",
//         message: "exceed max retry",
//         stack: "",
//       },
//     },
//     status: -1,
//     title: "WaitApi Failed.",
//   };
//   throw errorRes;
// };
