#!/usr/bin/env node

const cp = require("child_process");
const chalk = require("chalk");
require("dotenv").config();

const containerName = process.env.CONFIGURATOR_NAME;
const configuratorImage = process.env.CONFIGURATOR_IMAGE_NAME;
const masterIp = process.env.K8S_MASTER;
const userName = process.env.USER_NAME;

console.log(
  chalk.blue(
    `📃Start a ${chalk.underline(
      "fake mode"
    )} configurator named ${containerName} on ${masterIp}`
  )
);
console.log();

try {
  cp.execSync(
    `ssh ${userName}@${masterIp} docker run --rm -d --name ${containerName} -p 12345:12345 ${configuratorImage} --port 12345 --fake true`,
    { stdio: "inherit" }
  );

  console.log(
    chalk.green(
      `👍 Successfully created the configurator: ${chalk.bold(containerName)}`
    )
  );
} catch (error) {
  console.log(chalk.red(`Oops, we cannot start a new configurator`));
}
