#!/usr/bin/env node

const chalk = require("chalk");
const config = require("./config");
const { run } = require("./utils");
require("dotenv").config({ path: config.envPath });

const imageVersion = process.env.IMAGE_VERSION;
const configuratorImage = `oharastream/configurator:${imageVersion}`;
const images = [
  `oharastream/zookeeper:${imageVersion}`,
  `oharastream/broker:${imageVersion}`,
  `oharastream/connect-worker:${imageVersion}`,
  `oharastream/stream:${imageVersion}`
];

console.log(chalk.blue(`📃 Updating images`));
console.log();

const runMaster = run();
const runSlave = run({ isMaster: false });

runMaster("docker system prune -f");
runSlave("docker system prune -f");
runMaster(`docker pull ${configuratorImage}`);

images.forEach(image => runSlave(`docker pull ${image}`));
