#!/usr/bin/env node

const cp = require("child_process");
const chalk = require("chalk");
const config = require("./config");
const { runSsh } = require("./utils");
require("dotenv").config({ path: config.envPath });

const configuratorImage = process.env.CONFIGURATOR_IMAGE_NAME;

console.log(chalk.blue(`📃 Updating images`));
console.log();

runSsh({ command: `docker system prune -f` });
runSsh({ command: `docker system prune -f`, isSlave: true });
runSsh({ command: `docker pull ${configuratorImage}` });

const services = ["zookeeper", "broker", "connect-worker", "stream"];

services.forEach(service => {
  runSsh({
    command: `docker pull oharastream/${service}:0.9.0-SNAPSHOT`,
    isSlave: true
  });
});
